language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-graphicalmathpixi' ]; then cd .. && eval "mv $currentfolder generator-graphicalmathpixi" && cd generator-graphicalmathpixi; fi

